name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push_to_registry:
    name: building and pushing docker image to dockerhub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:v1

      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: docker push
        run: docker push docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_NAME }}:v1

  update_on_linode:
    name: updating docker image on EC2 using ssh
    needs: push_to_registry
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sudo docker stop invoice_management_server_container || true && sudo docker rm invoice_management_server_container || true && sudo docker pull docker.io/adisingh925/invoice-management-server-repository:v1 && sudo docker run -d --memory=100m -p 80:80 -p 443:443 --name invoice_management_server_container adisingh925/invoice-management-server-repository:v1 && exit
